AWSTemplateFormatVersion: 2010-09-09
Description: |
  Demo template for showroom to launch Atlassian ec2 instance/s.
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.medium
    AllowedValues:
      - t2.medium
      - t3.medium
      - t3.large
    Description: >
      Select t2.medium, t3.medium, or t3.large.  Default is t2.medium (t3.medium
      appears cheaper for same). See
      https://aws.amazon.com/ec2/pricing/on-demand/ to make an informed choice.
  InstanceKeyParameter:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: m_minaie_showroom
    Description: |
      Select an EC2 key pair to launch with your instance.
  InstanceSecurityGroupParameter:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: |
      Select a security group to launch with your instance.
Resources:
  showroomInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      ImageId: ami-0b727fc43dd53a80b
      KeyName: !Ref InstanceKeyParameter
      IamInstanceProfile: s3_read
      SecurityGroupIds: !Ref InstanceSecurityGroupParameter
      Tags:
        - 
          Key: Name
          Value: showroomDemo
        -
          Key: Environment
          Value: DevTest
        -
          Key: Project
          Value: showroom
        -
          Key: Component
          Value: Impact
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          date > /home/ec2-user/timing.txt #print time before update
          yum update -y
          aws s3 cp s3://showroomdocker/down/s3cp-down.tar.gz /home/ec2-user/
          su ec2-user -c '(cd /home/ec2-user/ && tar -xvf /home/ec2-user/s3cp-down.tar.gz)'
          sudo -H -u ec2-user bash -c '(cd /home/ec2-user/atlassianDocker/atlassianDocker/ && /usr/local/bin/docker-compose up -d)'
          rm -rf /home/ec2-user/s3cp-down.tar.gz
          date >> /home/ec2-user/timing.txt #print time after finished





#    InstanceSecurityGroup:
#        Type: AWS::EC2::SecurityGroup
#        Properties:
#            GroupName: !Ref InstanceSecurityGroupParameter
